location = /majoong { return 301 /majoong/; }
location /majoong/ {
  proxy_pass http://192.168.219.102:31443/;
  proxy_set_header Host $host;
  proxy_set_header X-Forwarded-Proto $scheme;
}
location /majoong/api/ {
  rewrite ^/majoong/(.*)$ /$1 break;
  proxy_pass http://192.168.219.102:31443;
  proxy_http_version 1.1;
  proxy_buffering off;
  proxy_read_timeout 130s;
}
