package kr.majoong;

import java.nio.charset.StandardCharsets;
import java.security.*;
import java.time.*;
import java.util.*;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.annotation.PostConstruct;
import jakarta.servlet.http.*;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.http.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.client.RestClient;
import org.springframework.web.util.WebUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@RestController
@RequestMapping("/api/v1")
public class Application {
  private static final ZoneId SEOUL=ZoneId.of("Asia/Seoul");
  private static final String OWNER_COOKIE="majoong_owner";
  private static final Logger LOG=LoggerFactory.getLogger(Application.class);
  private final String mode,icnServiceKey; private final RestClient http=RestClient.create();
  private final JdbcTemplate db; private final ObjectMapper json; private final StringRedisTemplate redis;
  private final SecureRandom random=new SecureRandom(); private final Object writeLock=new Object();
  public Application(@Value("${app.mode:demo}") String mode,@Value("${ICN_SERVICE_KEY:}") String icnServiceKey,JdbcTemplate db,ObjectMapper json,StringRedisTemplate redis){this.mode=mode;this.icnServiceKey=icnServiceKey;this.db=db;this.json=json;this.redis=redis;}
  @PostConstruct void schema(){
    db.execute("CREATE TABLE IF NOT EXISTS meetups (id VARCHAR(36) PRIMARY KEY, owner_hash VARCHAR(64) NOT NULL, revision BIGINT NOT NULL, flight VARCHAR(32) NOT NULL, origin VARCHAR(80) NOT NULL, destination VARCHAR(80) NOT NULL, scheduled VARCHAR(16) NOT NULL, estimated VARCHAR(16) NOT NULL, scheduled_date VARCHAR(10) NOT NULL, terminal VARCHAR(160) NOT NULL, arrival_exit VARCHAR(40) NOT NULL, baggage VARCHAR(40) NOT NULL, traveler_status VARCHAR(40) NOT NULL, note VARCHAR(300) NOT NULL, point_terminal VARCHAR(160) NOT NULL, point_area VARCHAR(120) NOT NULL, point_exit VARCHAR(40) NOT NULL, point_landmark VARCHAR(160) NOT NULL, completed BOOLEAN NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL)");
    db.execute("CREATE TABLE IF NOT EXISTS shares (token_hash VARCHAR(64) PRIMARY KEY, meetup_id VARCHAR(36) NOT NULL, expires_at TIMESTAMP WITH TIME ZONE NOT NULL, revoked BOOLEAN NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL)");
    db.execute("CREATE TABLE IF NOT EXISTS trips (id VARCHAR(36) PRIMARY KEY, owner_hash VARCHAR(64) NOT NULL, trip_type VARCHAR(20) NOT NULL, name VARCHAR(120) NOT NULL, segments_json CLOB NOT NULL, state VARCHAR(40) NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL)");
  }
  private boolean live(){return mode.equalsIgnoreCase("live");}
  @GetMapping("/flights") public Map<String,Object> flights(@RequestParam String arrivalDate,@RequestParam(required=false) String flightNumber,@RequestParam(defaultValue="ARRIVAL") String direction){LocalDate today=LocalDate.now(SEOUL),requested;try{requested="today".equalsIgnoreCase(arrivalDate)?today:LocalDate.parse(arrivalDate);}catch(Exception e){throw new DateOutOfRange("날짜는 YYYY-MM-DD 형식이어야 해요.");}if(requested.isBefore(today.minusDays(3))||requested.isAfter(today.plusDays(6)))throw new DateOutOfRange("조회 가능한 날짜는 "+today.minusDays(3)+"부터 "+today.plusDays(6)+"까지예요.");if(live())return liveFlights(requested.toString(),flightNumber,direction);return Map.of("query",Map.of("airport","ICN","direction",direction,"sourceLocalDate",requested.toString(),"zoneId","Asia/Seoul"),"coverage",Map.of("state","DEMO","reasonCode","DEMO_FIXTURE"),"items",List.of());}
  private Map<String,Object> liveFlights(String date,String flightNumber,String direction){
    if(icnServiceKey.isBlank())throw new SourceUnavailable("공항 데이터 인증이 설정되지 않았어요."); boolean departure="DEPARTURE".equalsIgnoreCase(direction);String cacheKey="majoong:flights:"+date+":"+(departure?"DEPARTURE":"ARRIVAL");Map<String,Object> cached=readCache(cacheKey);if(cached!=null){LOG.info("flight_lookup date={} direction={} cache=HIT",date,direction);return filter(cached,flightNumber);}
    try{JsonNodeResult result=fetchAll(date,departure);List<Map<String,Object>> items=new ArrayList<>();Instant seen=Instant.now();for(var row:result.rows){if(!row.schedule.startsWith(date.replace("-","")))continue;String raw=row.terminal;items.add(Map.ofEntries(Map.entry("id",row.id),Map.entry("displayNumber",row.number),Map.entry("origin",departure?"ICN":row.airportCode),Map.entry("originName",departure?"인천국제공항":row.airportName),Map.entry("destination",departure?row.airportCode:"ICN"),Map.entry("destinationName",departure?row.airportName:"인천국제공항"),Map.entry("scheduledLocalTime",time(row.schedule)),Map.entry("scheduledDate",date),Map.entry("estimatedLocalTime",time(row.estimated)),Map.entry("terminalRawCode",raw),Map.entry("terminalDisplayName",terminalDisplay(raw)),Map.entry("terminalMappingVersion","ICN_OPENAPI_GUIDE_2026-09"),Map.entry("arrivalExit",row.exit),Map.entry("baggageCarousel",row.baggage),Map.entry("status",row.status),Map.entry("dataMode","LIVE"),Map.entry("observedAt",seen.toString()),Map.entry("direction",departure?"DEPARTURE":"ARRIVAL"),Map.entry("source","ICN_DETAIL")));}
      boolean partial=result.partial;Map<String,Object> response=Map.of("query",Map.of("airport","ICN","direction",departure?"DEPARTURE":"ARRIVAL","sourceLocalDate",date,"zoneId","Asia/Seoul"),"items",items,"page",Map.of("returnedCount",items.size(),"upstreamTotal",result.total,"fetchedPages",result.pages,"nextPageAvailable",partial),"coverage",Map.of("state",partial?"PARTIAL":"COMPLETE","reasonCode",partial?"SOURCE_PAGE_FETCH_INCOMPLETE":"SOURCE_COMPLETE","coveredWindows",List.of("00:00-24:00")),"source",Map.of("dataMode","LIVE","lastSuccessfulCollectionAt",seen.toString(),"freshness","FRESH","cache","REDIS_900_SECONDS"),"sourceNote",partial?"일부 페이지를 가져오지 못했습니다. 잠시 후 다시 조회해 주세요.":"인천공항 상세 운항 API의 예정시각 기준 전체 조회 결과입니다.");writeCache(cacheKey,response);LOG.info("flight_lookup date={} direction={} cache=MISS items={} pages={} partial={}",date,direction,items.size(),result.pages,partial);return filter(response,flightNumber);
    }catch(SourceUnavailable e){throw e;}catch(Exception e){throw new SourceUnavailable("공항 정보 갱신이 지연되고 있어요.");}
  }
  private JsonNodeResult fetchAll(String date,boolean departure){JsonNodeResult first=fetch(date,departure,1);int expected=Math.max(1,(int)Math.ceil(Math.max(0,first.total)/100.0));if(expected>20)throw new SourceUnavailable("공항 데이터가 예상 범위를 초과했어요. 잠시 후 다시 조회해 주세요.");List<FlightRow> all=new ArrayList<>(first.rows);boolean partial=false;for(int page=2;page<=expected;page++){try{all.addAll(fetch(date,departure,page).rows);}catch(SourceUnavailable e){partial=true;break;}}return new JsonNodeResult(first.total,all,Math.min(expected,partial?Math.max(1,(all.size()+99)/100):expected),partial);}
  private JsonNodeResult fetch(String date,boolean departure,int pageNo){var root=http.get().uri(b->b.scheme("https").host("apis.data.go.kr").path(departure?"/B551177/statusOfAllFltDeOdp/getFltDeparturesDeOdp":"/B551177/statusOfAllFltDeOdp/getFltArrivalsDeOdp").queryParam("serviceKey",icnServiceKey).queryParam("type","json").queryParam("searchdtCode","S").queryParam("searchDate",date.replace("-","")).queryParam("searchFrom","0000").queryParam("searchTo","2400").queryParam("passengerOrCargo","P").queryParam("numOfRows",100).queryParam("pageNo",pageNo).build()).retrieve().body(com.fasterxml.jackson.databind.JsonNode.class);if(root==null||!"00".equals(root.path("response").path("header").path("resultCode").asText()))throw new SourceUnavailable("공항 데이터 원본이 응답하지 않았어요.");var body=root.path("response").path("body");List<FlightRow> rows=new ArrayList<>();for(var r:body.path("items"))rows.add(new FlightRow(r.path("fid").asText("unknown"),r.path("flightId").asText("").replace(" ",""),r.path("scheduleDatetime").asText(""),r.path("estimatedDatetime").asText(""),r.path("airportCode").asText("unknown"),r.path("airport").asText("미정"),r.path("terminalId").asText("unknown"),r.path("exitNumber").asText("미정"),r.path("carousel").asText("미정"),r.path("remark").asText("상태 확인 중")));return new JsonNodeResult(body.path("totalCount").asInt(-1),rows,pageNo,false);}
  @SuppressWarnings("unchecked") private Map<String,Object> readCache(String key){try{String value=redis.opsForValue().get(key);return value==null?null:json.readValue(value,new TypeReference<Map<String,Object>>(){});}catch(Exception e){return null;}}
  private void writeCache(String key,Map<String,Object> value){try{redis.opsForValue().set(key,json.writeValueAsString(value),Duration.ofMinutes(15));}catch(Exception ignored){}}
  @SuppressWarnings("unchecked") private Map<String,Object> filter(Map<String,Object> base,String query){if(query==null||query.isBlank())return base;String q=query.replaceAll("\\s","").toUpperCase(Locale.ROOT);List<Map<String,Object>> items=((List<Map<String,Object>>)base.get("items")).stream().filter(x->matches(x,q)).toList();Map<String,Object> out=new LinkedHashMap<>(base);out.put("items",items);Map<String,Object> page=new LinkedHashMap<>((Map<String,Object>)base.get("page"));page.put("returnedCount",items.size());out.put("page",page);return out;}
  private boolean matches(Map<String,Object> item,String query){return List.of("displayNumber","origin","originName","destination","destinationName").stream().map(k->String.valueOf(item.get(k)).replaceAll("\\s","").toUpperCase(Locale.ROOT)).anyMatch(v->v.contains(query));}
  private String time(String value){return value!=null&&value.length()>=12?value.substring(8,10)+":"+value.substring(10,12):"미정";}
  private String terminalDisplay(String raw){return switch(raw==null?"":raw){case "P01"->"제1여객터미널";case "P02"->"탑승동";case "P03"->"제2여객터미널";default->"터미널 확인 중"+(raw==null||raw.isBlank()||raw.equals("unknown")?"":" (원본 "+raw+")");};}
  @GetMapping("/source-status") public Map<String,Object> source(){LocalDate today=LocalDate.now(SEOUL);return Map.of("enabled",live(),"mode",mode.toUpperCase(),"coverage","SOURCE_PAGINATED","serverLocalDate",today.toString(),"searchDateFrom",today.minusDays(3).toString(),"searchDateTo",today.plusDays(6).toString(),"cache","REDIS_900_SECONDS");}
  @GetMapping("/airport-guides") public List<Map<String,Object>> airportGuides(){return List.of(
    guide("ICN","인천국제공항","제1·제2여객터미널과 탑승동","안내·환전·의료·교통약자 서비스","https://www.airport.kr/ap_ko/index.do","https://www.airport.kr/ap_ko/1376/subview.do","인천국제공항공사"),
    guide("GMP","김포국제공항","국내선·국제선 층별 지도","식당·카페·라운지·수유실·AED","https://www.airport.co.kr/gimpo/cms/frFacCon/facilityMapList.do?MENU_ID=1420&acd=A1101&listGbn=2","https://www.airport.co.kr/gimpo/cms/frFacCon/facilityList.do?MENU_ID=1420&acd=A1101&listGbn=1","한국공항공사"),
    guide("CJU","제주국제공항","국내선·국제선 층별 지도","식당·카페·라운지·교통약자 시설·AED","https://www.airport.co.kr/jeju/cms/frFacCon/facilityMapList.do?MENU_ID=160&acd=A1103&listGbn=2","https://www.airport.co.kr/jeju/cms/frFacCon/facilityList.do?MENU_ID=160&acd=A1103&listGbn=1","한국공항공사"),
    guide("PUS","김해국제공항","국내선·국제선 층별 지도","식당·로밍·충전·의료·교통약자 시설","https://www.airport.co.kr/gimhae/cms/frFacCon/facilityMapList.do?MENU_ID=220&acd=A1102&listGbn=2","https://www.airport.co.kr/gimhae/cms/frFacCon/facilityList.do?MENU_ID=220&acd=A1102&listGbn=1","한국공항공사"));}
  private Map<String,Object> guide(String code,String name,String mapSummary,String facilities,String mapUrl,String facilityUrl,String operator){return Map.of("code",code,"name",name,"mapSummary",mapSummary,"facilities",facilities,"mapUrl",mapUrl,"facilityUrl",facilityUrl,"operator",operator,"verifiedAt","2026-09-22");}
  @PostMapping("/meetups") @ResponseStatus(HttpStatus.CREATED) public Meetup create(@Valid @RequestBody CreateMeetupRequest r,HttpServletRequest req,HttpServletResponse res){String owner=owner(req,res),id=UUID.randomUUID().toString();Instant now=Instant.now();String date=r.scheduledDate()==null||r.scheduledDate().isBlank()?LocalDate.now(SEOUL).toString():r.scheduledDate();db.update("INSERT INTO meetups VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",id,owner,1,r.flightNumber().replaceAll("\\s",""),r.origin(),r.destination(),r.scheduledLocalTime(),r.estimatedLocalTime(),date,r.terminalDisplayName(),r.arrivalExit(),r.baggageCarousel(),"NOT_SHARED","","","","","",false,now);return require(id);}
  @GetMapping("/meetups/{id}") public Meetup meetup(@PathVariable String id,HttpServletRequest req,HttpServletResponse res){noStore(res);Meetup m=require(id);own(m,req);return m;}
  @PatchMapping("/meetups/{id}/traveler-status") public Meetup status(@PathVariable String id,@Valid @RequestBody StatusRequest r,HttpServletRequest req,HttpServletResponse res){noStore(res);Meetup m=require(id);own(m,req);if(!Set.of("IMMIGRATION","WAITING_BAGGAGE","OUTSIDE","MET","NOT_SHARED").contains(r.status()))throw new Bad();update(id,r.expectedVersion(),"UPDATE meetups SET traveler_status=?, revision=revision+1, updated_at=? WHERE id=? AND revision=?",r.status(),Instant.now());return require(id);}
  @PatchMapping("/meetups/{id}/meeting-note") public Meetup note(@PathVariable String id,@Valid @RequestBody NoteRequest r,HttpServletRequest req,HttpServletResponse res){noStore(res);Meetup m=require(id);own(m,req);update(id,r.expectedVersion(),"UPDATE meetups SET note=?, revision=revision+1, updated_at=? WHERE id=? AND revision=?",r.text(),Instant.now());return require(id);}
  @PatchMapping("/meetups/{id}/meeting-point") public Meetup point(@PathVariable String id,@Valid @RequestBody MeetingPointRequest r,HttpServletRequest req,HttpServletResponse res){noStore(res);Meetup m=require(id);own(m,req);update(id,r.expectedVersion(),"UPDATE meetups SET point_terminal=?,point_area=?,point_exit=?,point_landmark=?,note=?,revision=revision+1,updated_at=? WHERE id=? AND revision=?",r.terminal(),r.publicArea(),r.exitLabel(),r.landmark(),r.note(),Instant.now());return require(id);}
  @PostMapping("/meetups/{id}/complete") public Meetup complete(@PathVariable String id,@Valid @RequestBody CompleteRequest r,HttpServletRequest req,HttpServletResponse res){noStore(res);Meetup m=require(id);own(m,req);synchronized(writeLock){update(id,r.expectedVersion(),"UPDATE meetups SET traveler_status='MET',completed=TRUE,revision=revision+1,updated_at=? WHERE id=? AND revision=?",Instant.now());db.update("UPDATE shares SET revoked=TRUE WHERE meetup_id=?",id);}return require(id);}
  @PostMapping("/meetups/{id}/shares") @ResponseStatus(HttpStatus.CREATED) public Map<String,Object> share(@PathVariable String id,HttpServletRequest req,HttpServletResponse res){noStore(res);Meetup m=require(id);own(m,req);if(m.completed)throw new Gone();byte[] bytes=new byte[32];random.nextBytes(bytes);String token=Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);Instant expiry=Instant.now().plus(Duration.ofHours(24));db.update("INSERT INTO shares VALUES (?,?,?,?,?)",hash(token),id,expiry,false,Instant.now());return Map.of("url","/majoong/s#token="+token,"expiresAt",expiry.toString(),"urlAvailable",true,"scope","항공편·공식 공항 정보·여행자가 입력한 상태와 만남 장소");}
  @PostMapping("/shares/exchange") public Map<String,Object> exchange(@Valid @RequestBody TokenRequest body,HttpServletResponse res){noStore(res);try{Share s=db.queryForObject("SELECT token_hash,meetup_id,expires_at,revoked FROM shares WHERE token_hash=?",(rs,n)->new Share(rs.getString(1),rs.getString(2),rs.getObject(3,Instant.class),rs.getBoolean(4)),hash(body.token()));if(s.revoked||s.expiry.isBefore(Instant.now())||require(s.meetup).completed)throw new Gone();return shared(require(s.meetup));}catch(EmptyResultDataAccessException e){throw new Gone();}}
  @PostMapping("/trips") @ResponseStatus(HttpStatus.CREATED) public Map<String,Object> trip(@Valid @RequestBody TripRequest r,HttpServletRequest req,HttpServletResponse res)throws Exception{String owner=owner(req,res);validateTrip(r);String id=UUID.randomUUID().toString();db.update("INSERT INTO trips VALUES (?,?,?,?,?,?,?)",id,owner,r.type(),r.name(),json.writeValueAsString(r.segments()),"MANUAL_UNVERIFIED",Instant.now());return Map.of("id",id,"type",r.type(),"state","MANUAL_UNVERIFIED","message","직접 등록한 일정이에요. 당일 정보와 연결할 예정이에요.");}
  @GetMapping("/trips") public List<Map<String,Object>> trips(HttpServletRequest req,HttpServletResponse res){noStore(res);String owner=existingOwner(req);if(owner==null)return List.of();return db.query("SELECT id,trip_type,name,segments_json,state,created_at FROM trips WHERE owner_hash=? ORDER BY created_at DESC",(rs,n)->Map.of("id",rs.getString(1),"type",rs.getString(2),"name",rs.getString(3),"segments",readSegments(rs.getString(4)),"state",rs.getString(5),"createdAt",rs.getObject(6,Instant.class).toString()),owner);}
  @DeleteMapping("/trips/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void deleteTrip(@PathVariable String id,HttpServletRequest req,HttpServletResponse res){noStore(res);String owner=existingOwner(req);if(owner==null||db.update("DELETE FROM trips WHERE id=? AND owner_hash=?",id,owner)!=1)throw new Missing();}
  private Object readSegments(String value){try{return json.readValue(value,Object.class);}catch(Exception e){throw new IllegalStateException("저장된 일정 형식을 읽을 수 없어요.");}}
  private void validateTrip(TripRequest r){if(!Set.of("ONE_WAY","ROUND_TRIP","MULTI_CITY").contains(r.type()))throw new Bad("여정 유형이 올바르지 않아요.");if(r.type().equals("ONE_WAY")&&r.segments().size()!=1)throw new Bad("편도는 한 구간만 등록할 수 있어요.");if(r.type().equals("ROUND_TRIP")&&r.segments().size()!=2)throw new Bad("왕복은 가는 편과 오는 편 두 구간이 필요해요.");if(r.type().equals("MULTI_CITY")&&r.segments().size()<2)throw new Bad("다구간은 두 구간 이상이 필요해요.");LocalDate previous=null;for(TripSegment s:r.segments()){if(!s.origin().matches("(?i)[A-Z]{3}")||!s.destination().matches("(?i)[A-Z]{3}"))throw new Bad("출발·도착 공항은 3자리 IATA 코드로 입력해 주세요.");LocalDate date=LocalDate.parse(s.date());if(previous!=null&&date.isBefore(previous))throw new Bad("여정 날짜는 시간순으로 입력해 주세요.");previous=date;}if(r.type().equals("ROUND_TRIP")&&(!r.segments().get(0).destination().equalsIgnoreCase(r.segments().get(1).origin())||!r.segments().get(0).origin().equalsIgnoreCase(r.segments().get(1).destination())))throw new Bad("왕복의 출발·도착 공항이 서로 맞지 않아요.");}
  private void update(String id,long version,String sql,Object... values){Object[] p=Arrays.copyOf(values,values.length+2);p[p.length-2]=id;p[p.length-1]=version;if(db.update(sql,p)!=1)throw new Conflict();}
  private Meetup require(String id){try{return db.queryForObject("SELECT id,owner_hash,revision,flight,origin,destination,scheduled,estimated,scheduled_date,terminal,arrival_exit,baggage,traveler_status,note,point_terminal,point_area,point_exit,point_landmark,completed,updated_at FROM meetups WHERE id=?",(rs,n)->new Meetup(rs.getString(1),rs.getString(2),rs.getLong(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12),rs.getString(13),rs.getString(14),rs.getString(15),rs.getString(16),rs.getString(17),rs.getString(18),rs.getBoolean(19),rs.getObject(20,Instant.class)),id);}catch(EmptyResultDataAccessException e){throw new Missing();}}
  private void own(Meetup m,HttpServletRequest req){String owner=existingOwner(req);if(owner==null||!MessageDigest.isEqual(m.ownerHash.getBytes(StandardCharsets.UTF_8),owner.getBytes(StandardCharsets.UTF_8)))throw new Missing();}
  private String owner(HttpServletRequest req,HttpServletResponse res){String value=cookie(req);if(value==null){byte[] b=new byte[32];random.nextBytes(b);value=Base64.getUrlEncoder().withoutPadding().encodeToString(b);res.addHeader(HttpHeaders.SET_COOKIE,ResponseCookie.from(OWNER_COOKIE,value).httpOnly(true).secure(true).sameSite("Strict").path("/majoong/").maxAge(Duration.ofDays(90)).build().toString());}return hash(value);}
  private String existingOwner(HttpServletRequest req){String token=cookie(req);return token==null?null:hash(token);}private String cookie(HttpServletRequest req){var c=WebUtils.getCookie(req,OWNER_COOKIE);return c==null?null:c.getValue();}private String hash(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}private void noStore(HttpServletResponse r){r.setHeader(HttpHeaders.CACHE_CONTROL,"no-store");r.setHeader("Pragma","no-cache");}
  private Map<String,Object> shared(Meetup m){return Map.ofEntries(Map.entry("meetupId",m.id),Map.entry("revision",m.revision),Map.entry("flight",Map.of("displayNumber",m.flight,"origin",m.origin,"destination",m.destination)),Map.entry("arrival",Map.of("scheduledLocalTime",m.scheduled,"estimatedLocalTime",m.estimated,"date",m.scheduledDate,"dateConfidence","USER_OR_SOURCE_DATE","zoneId","Asia/Seoul")),Map.entry("airportInfo",Map.of("terminal",m.terminal,"arrivalExit",m.exit,"baggageCarousel",m.baggage)),Map.entry("traveler",Map.of("status",m.status,"updatedAt",m.updatedAt.toString())),Map.entry("meetingPoint",Map.of("terminal",m.pointTerminal,"publicArea",m.pointArea,"exitLabel",m.pointExit,"landmark",m.pointLandmark,"sourceType",m.pointTerminal.isBlank()?"NONE":"USER_CONFIRMED")),Map.entry("meetingNote",m.note),Map.entry("dataMode",mode.toUpperCase()),Map.entry("officialDataState","SNAPSHOT_AT_CREATION"),Map.entry("travelerUpdatedAt",m.updatedAt.toString()));}
  public static class Meetup {public String id,flight,origin,destination,scheduled,estimated,scheduledDate,terminal,exit,baggage,status,note,pointTerminal,pointArea,pointExit,pointLandmark;public long revision;public boolean completed;@JsonIgnore public String ownerHash;public Instant updatedAt;Meetup(String i,String o,long r,String f,String or,String d,String sc,String es,String sd,String t,String e,String b,String s,String n,String pt,String pa,String pe,String pl,boolean c,Instant u){id=i;ownerHash=o;revision=r;flight=f;origin=or;destination=d;scheduled=sc;estimated=es;scheduledDate=sd;terminal=t;exit=e;baggage=b;status=s;note=n;pointTerminal=pt;pointArea=pa;pointExit=pe;pointLandmark=pl;completed=c;updatedAt=u;}}
  record FlightRow(String id,String number,String schedule,String estimated,String airportCode,String airportName,String terminal,String exit,String baggage,String status){}record JsonNodeResult(int total,List<FlightRow> rows,int pages,boolean partial){}record Share(String tokenHash,String meetup,Instant expiry,boolean revoked){}record CreateMeetupRequest(@NotBlank String flightNumber,@NotBlank String origin,@NotBlank String destination,@NotBlank String scheduledLocalTime,@NotBlank String estimatedLocalTime,@Pattern(regexp="\\d{4}-\\d{2}-\\d{2}") String scheduledDate,@NotBlank String terminalDisplayName,@NotBlank String arrivalExit,@NotBlank String baggageCarousel){}record StatusRequest(@NotBlank String status,@PositiveOrZero long expectedVersion){}record NoteRequest(@NotBlank @Size(max=300) String text,@PositiveOrZero long expectedVersion){}record MeetingPointRequest(@NotBlank @Size(max=160) String terminal,@NotBlank @Size(max=120) String publicArea,@NotBlank @Size(max=40) String exitLabel,@NotBlank @Size(max=160) String landmark,@NotBlank @Size(max=300) String note,@PositiveOrZero long expectedVersion){}record CompleteRequest(@PositiveOrZero long expectedVersion){}record TokenRequest(@NotBlank @Size(max=128) String token){}record TripSegment(@NotBlank @Pattern(regexp="(?i)[A-Z0-9]{2,20}") String flightNumber,@Pattern(regexp="\\d{4}-\\d{2}-\\d{2}") String date,@NotBlank String dateBasis,@NotBlank String origin,@NotBlank String destination,@Size(max=80) String airline,@Size(max=40) String bookingReference,@Size(max=5) String departureTime,@Size(max=5) String arrivalTime,@Size(max=40) String terminal,@Size(max=20) String gate,@Size(max=20) String seat,@Size(max=80) String baggage,@Size(max=300) String memo){}record TripRequest(@NotBlank String type,@NotBlank @Size(max=120) String name,@NotEmpty List<@Valid TripSegment> segments){}
  @ExceptionHandler({Bad.class,DateOutOfRange.class}) ResponseEntity<Map<String,String>> badInput(RuntimeException e){return ResponseEntity.badRequest().body(Map.of("message",e.getMessage()==null?"입력값을 확인해 주세요.":e.getMessage()));}
  @ResponseStatus(HttpStatus.CONFLICT) static class Conflict extends RuntimeException{}@ResponseStatus(HttpStatus.GONE) static class Gone extends RuntimeException{}@ResponseStatus(HttpStatus.BAD_REQUEST) static class Bad extends RuntimeException{Bad(){super("입력값을 확인해 주세요.");}Bad(String m){super(m);}}@ResponseStatus(HttpStatus.BAD_REQUEST) static class DateOutOfRange extends RuntimeException{DateOutOfRange(String m){super(m);}}@ResponseStatus(HttpStatus.NOT_FOUND) static class Missing extends RuntimeException{}@ResponseStatus(HttpStatus.SERVICE_UNAVAILABLE) static class SourceUnavailable extends RuntimeException{SourceUnavailable(String m){super(m);}}
}
