const A='/majoong/api/v1',app=document.querySelector('#app');
const state={source:null,rows:[],selected:null,displayLimit:50,filter:'',controller:null,observer:null,routeToken:0,tripDraft:null,trips:[],meetups:[],shareTimer:null,revealed:new Set(),linking:null,resumeDraft:false};
const e=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Seoul'});
const offsetDate=n=>{const d=new Date(today()+'T12:00:00+09:00');d.setDate(d.getDate()+n);return d.toLocaleDateString('en-CA',{timeZone:'Asia/Seoul'})};
const fmtDate=value=>{try{return new Intl.DateTimeFormat('ko-KR',{month:'short',day:'numeric',weekday:'short',timeZone:'Asia/Seoul'}).format(new Date(value+'T12:00:00+09:00'))}catch{return value}};
const fmtTime=value=>{try{return new Intl.DateTimeFormat('ko-KR',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Seoul'}).format(new Date(value))}catch{return value}};
const statusLabel=value=>({NOT_SHARED:'아직 공유 안 함',IMMIGRATION:'입국심사 중',WAITING_BAGGAGE:'짐 기다리는 중',OUTSIDE:'밖으로 나왔어요',MET:'만났어요'}[value]||value||'상태 미공유');
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,2600)}
async function api(path,options={}){const response=await fetch(A+path,options);let data=null;try{data=await response.json()}catch{}if(!response.ok){const error=new Error(data?.message||'요청을 처리하지 못했어요.');error.status=response.status;error.code=data?.code;error.retryable=data?.retryable;throw error}return data}
function navigate(path,{replace=false}={}){if(location.pathname+location.search!==path){history[replace?'replaceState':'pushState']({},'',path)}route()}
function hero(label,title,copy){return `<section class="hero"><div class="hero-copy"><div class="eyebrow">${e(label)}</div><h1>${title}</h1><p>${e(copy)}</p></div><img class="pilot" src="/majoong/assets/gureumi-hero-v1.png" alt="구름이 조종사"></section>`}
function empty(icon,title,copy,action=''){return `<section class="card empty"><div class="empty-emoji">${icon}</div><h2>${e(title)}</h2><p class="muted">${e(copy)}</p>${action}</section>`}
async function loadSource(){if(!state.source)state.source=await api('/source-status');return state.source}

async function route(){
  const token=++state.routeToken;clearInterval(state.shareTimer);state.controller?.abort();state.observer?.disconnect();closeNotifications();
  const path=location.pathname.replace(/\/+$/,'')||'/majoong';
  try{
    if(path==='/majoong/s')return sharedView(token);
    if(path==='/majoong/trips/new')return tripFormView(null,token);
    const tripMatch=path.match(/^\/majoong\/trips\/([^/]+)$/);if(tripMatch)return tripFormView(tripMatch[1],token);
    if(path==='/majoong/trips')return tripsView(token);
    const meetupMatch=path.match(/^\/majoong\/meetups\/([^/]+)$/);if(meetupMatch)return meetupDetailView(meetupMatch[1],token);
    if(path==='/majoong/meetups')return meetupsView(token);
    return homeView(token);
  }catch(error){if(token!==state.routeToken)return;app.innerHTML=empty('☁️','화면을 불러오지 못했어요',error.message,`<button class="primary" data-action="retry-route">다시 시도</button>`)}
}

async function homeView(token){
  const source=await loadSource();if(token!==state.routeToken)return;
  const params=new URLSearchParams(location.search),date=params.get('date')||source.serverLocalDate||today(),direction=params.get('direction')||'ARRIVAL',q=params.get('q')||'';
  const linkingHint=state.linking?`<div class="notice info">${e(state.linking.label)} 구간에 선택한 실제 운항편을 연결하고 있어요. <button class="text-button" type="button" data-action="cancel-linking">연결 취소</button></div>`:'';
  app.innerHTML=hero('INCHEON AIRPORT','비행기를 찾고,<br>만날 순간까지 이어보세요.','날짜와 방향을 골라 인천공항 공식 운항 정보를 확인하세요.')+linkingHint+`
    <form id="searchForm" class="search-panel">
      <div class="direction-tabs" role="group" aria-label="운항 방향"><button type="button" data-action="direction" data-value="ARRIVAL" aria-pressed="${direction==='ARRIVAL'}">인천 도착</button><button type="button" data-action="direction" data-value="DEPARTURE" aria-pressed="${direction==='DEPARTURE'}">인천 출발</button></div>
      <div class="search-grid"><label class="field"><span id="dateLabel">${direction==='ARRIVAL'?'도착일':'출발일'}</span><input class="input" id="flightDate" type="date" min="${e(source.searchDateFrom)}" max="${e(source.searchDateTo)}" value="${e(date)}" required></label>
      <label class="field">편명 또는 도시·공항<input class="input" id="flightQuery" value="${e(q)}" placeholder="예: CX426, 홍콩, HKG"></label><button class="primary" id="searchButton" type="submit">항공편 찾기</button></div>
      <div class="quick-days"><span class="muted small">빠른 날짜</span><button type="button" data-action="quick-date" data-value="-1">어제</button><button type="button" data-action="quick-date" data-value="0">오늘</button><button type="button" data-action="quick-date" data-value="1">내일</button><span class="muted small">조회 범위 ${e(source.searchDateFrom)} ~ ${e(source.searchDateTo)}</span></div>
    </form>
    <section class="section content-grid"><div><div class="result-head"><div><h2 class="section-title" id="resultTitle">${direction==='ARRIVAL'?'인천 도착편':'인천 출발편'}</h2><p class="muted" id="resultCopy">공식 운항 정보를 확인하고 있어요.</p></div></div><div id="sourceNotice" aria-live="polite"></div><div class="card"><div class="filter-row"><label class="sr" for="resultFilter">현재 결과 내 검색</label><input class="input" id="resultFilter" placeholder="현재 목록에서 편명·공항으로 좁히기"><button class="text-button" type="button" data-action="clear-filter">초기화</button></div><div class="result-list" id="flightList"><div class="loading">항공편을 불러오는 중이에요.</div></div></div></div>
    <aside class="detail-column" id="detailColumn"><div class="card sticky detail" id="flightDetail"><h2>항공편을 선택하세요</h2><p class="muted">목록에서 고르면 시각과 장소, 여행 지갑과 마중 기능을 사용할 수 있어요.</p></div></aside></section>
    <section class="section"><h2 class="section-title">공항 지도·편의시설</h2><p class="muted">운영기관이 제공하는 공식 안내로 연결합니다.</p><div id="airportGuides" class="guide-grid"><div class="card loading">공항 안내를 불러오는 중이에요.</div></div></section>`;
  bindSearch();await Promise.allSettled([searchFlights({restoreFlight:params.get('flight')}),loadGuides()]);
}
function bindSearch(){document.querySelector('#searchForm').addEventListener('submit',event=>{event.preventDefault();searchFlights()});document.querySelector('#resultFilter').addEventListener('input',event=>{state.filter=event.target.value;state.displayLimit=50;renderFlights()})}
async function searchFlights({restoreFlight=null}={}){
  const date=document.querySelector('#flightDate').value,direction=document.querySelector('[data-action="direction"][aria-pressed="true"]').dataset.value,q=document.querySelector('#flightQuery').value.trim(),button=document.querySelector('#searchButton');
  state.controller?.abort();const controller=new AbortController();state.controller=controller;state.filter='';state.displayLimit=50;state.selected=null;document.querySelector('#resultFilter').value='';document.querySelector('#resultTitle').textContent=direction==='ARRIVAL'?'인천 도착편':'인천 출발편';document.querySelector('#detailColumn').classList.remove('open');document.querySelector('#flightDetail').innerHTML='<h2>항공편을 선택하세요</h2><p class="muted">목록에서 고르면 시각과 장소를 확인할 수 있어요.</p>';button.disabled=true;document.querySelector('#flightList').innerHTML='<div class="loading">공식 운항 정보를 확인하고 있어요.</div>';
  const params=new URLSearchParams({date,direction});if(q)params.set('q',q);history.replaceState({},'',location.pathname+'?'+params);
  try{
    const response=await api('/flights?'+new URLSearchParams({date,direction,q}),{signal:controller.signal});if(controller!==state.controller)return;
    state.rows=response.items||[];const total=response.page?.returnedCount??state.rows.length,partial=response.coverage?.state==='PARTIAL';document.querySelector('#resultCopy').textContent=`검색 결과 ${total.toLocaleString()}건 · 모든 시각은 인천공항 현지시각입니다.`;
    const freshness=response.source?.freshness==='FRESH'?'최근 확인':response.source?.freshness==='STALE'?'정보 갱신이 지연됨':'오래된 확인 정보';
    document.querySelector('#sourceNotice').innerHTML=`<div class="notice ${partial?'':'info'}">${partial?'일부 페이지를 가져오지 못했어요. ':''}${freshness} ${e(fmtTime(response.source?.lastSuccessfulCollectionAt))}${response.source?.ageSeconds!=null?' · '+Math.floor(response.source.ageSeconds/60)+'분 전':''}</div>`;renderFlights();
    if(restoreFlight){const found=state.rows.find(row=>row.id===restoreFlight);if(found)selectFlight(found.id,{updateUrl:false})}
  }catch(error){if(error.name==='AbortError')return;state.rows=[];document.querySelector('#sourceNotice').innerHTML='';document.querySelector('#flightList').innerHTML=`<div class="notice error">${e(error.message)} ${error.retryable?'<button class="text-button" data-action="search">다시 시도</button>':''}</div>`}finally{if(controller===state.controller)button.disabled=false}
}
function filteredRows(){const term=state.filter.trim().replaceAll(' ','').toUpperCase();return term?state.rows.filter(row=>[row.displayNumber,row.origin,row.originName,row.destination,row.destinationName].some(value=>String(value||'').replaceAll(' ','').toUpperCase().includes(term))):state.rows}
function renderFlights(){
  state.observer?.disconnect();const list=document.querySelector('#flightList');if(!list)return;const filtered=filteredRows(),shown=filtered.slice(0,state.displayLimit),direction=document.querySelector('[data-action="direction"][aria-pressed="true"]')?.dataset.value||'ARRIVAL';
  if(!filtered.length){list.innerHTML=state.rows.length?`<div class="empty"><h3>필터에 맞는 항공편이 없어요</h3><p class="muted">필터를 지우면 검색 결과 ${state.rows.length}건을 볼 수 있어요.</p><button class="secondary" data-action="clear-filter">필터 지우기</button></div>`:`<div class="empty"><h3>조건에 맞는 항공편이 없어요</h3><p class="muted">날짜나 도시를 바꾸거나 여행 지갑에 직접 등록할 수 있어요.</p><button class="secondary" data-route="/majoong/trips/new">직접 일정 등록</button></div>`;return}
  list.innerHTML=shown.map(row=>`<article class="flight"><div class="flight-icon" aria-hidden="true">✈</div><div><div class="flight-number">${e(row.displayNumber)}</div><div class="flight-route">${e(row.originName)} (${e(row.origin)}) → ${e(row.destinationName)} (${e(row.destination)})</div><div class="flight-meta">${e(row.scheduledDate)} · ${e(row.status)} · ${e(row.terminalDisplayName)}${direction==='ARRIVAL'?' · 입국 출구 '+e(row.arrivalExit):''}</div></div><div class="flight-time">${e(row.estimatedLocalTime)}<small>예정 ${e(row.scheduledLocalTime)}</small><button class="choose" data-action="select-flight" data-id="${e(row.id)}" aria-label="${e(row.displayNumber)} 항공편 선택">선택</button></div></article>`).join('')+(shown.length<filtered.length?`<div id="scrollSentinel" class="sentinel">${shown.length} / ${filtered.length}편 표시<br><button class="secondary" data-action="more-flights">더 보기</button></div>`:`<div class="sentinel">${filtered.length}편을 모두 표시했어요.</div>`);
  const sentinel=document.querySelector('#scrollSentinel');if(sentinel&&'IntersectionObserver'in window){state.observer=new IntersectionObserver(entries=>{if(entries.some(entry=>entry.isIntersecting)){state.displayLimit+=50;renderFlights()}},{root:matchMedia('(max-width:720px)').matches?null:list,rootMargin:'180px'});state.observer.observe(sentinel)}
}
function selectFlight(id,{updateUrl=true}={}){
  const row=state.rows.find(item=>item.id===id);if(!row)return;state.selected=row;const direction=row.direction||'ARRIVAL',detail=document.querySelector('#flightDetail');
  const tripAction=state.linking?'<button class="primary wide" data-action="link-flight-trip">이 구간에 연결</button>':'<button class="primary wide" data-action="add-flight-trip">여행 지갑에 담기</button>';
  detail.innerHTML=`<button class="text-button mobile-detail-close" data-action="close-detail">목록으로</button><span class="source-badge">인천공항 공식 데이터</span><h2 tabindex="-1">${e(row.displayNumber)}</h2><p class="muted">${e(row.originName)} (${e(row.origin)}) → ${e(row.destinationName)} (${e(row.destination)}) · ${e(row.scheduledDate)}</p><div class="big-time">${e(row.estimatedLocalTime)}</div><p class="muted">예정 ${e(row.scheduledLocalTime)} · ${e(row.status)}</p><div class="data-grid"><div><small>터미널</small><b>${e(row.terminalDisplayName)}</b></div><div><small>${direction==='ARRIVAL'?'입국 출구':'방향'}</small><b>${direction==='ARRIVAL'?e(row.arrivalExit):'인천 출발'}</b></div><div><small>수하물 수취대</small><b>${direction==='ARRIVAL'?e(row.baggageCarousel):'해당 없음'}</b></div><div><small>최근 확인</small><b>${e(fmtTime(row.observedAt))}</b></div></div><div class="stack">${tripAction}${direction==='ARRIVAL'?'<button class="secondary wide" data-action="create-meetup">이 항공편으로 마중방 만들기</button>':''}<button class="secondary wide" data-action="watch-flight">변경 알림함에 추가</button><a class="secondary wide" href="https://www.airport.kr/geomap/ap_ko/view.do?type=2&alertType=0&tmnlId=P01" target="_blank" rel="noopener noreferrer" style="text-align:center;text-decoration:none">인천공항 공식 지도</a></div>`;
  document.querySelector('#detailColumn').classList.add('open');if(updateUrl){const params=new URLSearchParams(location.search);params.set('flight',id);history.replaceState({},'',location.pathname+'?'+params)}if(matchMedia('(max-width:720px)').matches)detail.querySelector('h2').focus?.();
}
async function loadGuides(){try{const items=await api('/airport-guides'),box=document.querySelector('#airportGuides');if(!box)return;box.innerHTML=items.map(item=>`<article class="card guide-card"><span class="source-badge">${e(item.code)} · ${e(item.operator)}</span><h3>${e(item.name)}</h3><p class="muted">${e(item.mapSummary)}</p><p>${e(item.facilities)}</p><div class="guide-links"><a href="${e(item.mapUrl)}" target="_blank" rel="noopener noreferrer">공식 지도</a><a href="${e(item.facilityUrl)}" target="_blank" rel="noopener noreferrer">편의시설</a></div><p class="muted small">확인 ${e(item.verifiedAt)}</p></article>`).join('')}catch{document.querySelector('#airportGuides').innerHTML='<div class="card muted">공항 안내를 불러오지 못했어요.</div>'}}

function blankSegment(prefill={}){return {segmentId:crypto.randomUUID(),flightNumber:'',date:today(),dateBasis:'DEPARTURE_LOCAL_DATE',origin:'ICN',destination:'',airline:'',bookingReference:'',departureTime:'',arrivalTime:'',terminal:'',gate:'',seat:'',baggage:'',memo:'',providerId:'',direction:'',sourceState:'MANUAL_UNVERIFIED',...prefill}}
function flightSegment(row,existing={}){const arrival=row.direction==='ARRIVAL';return {...existing,flightNumber:row.displayNumber,date:row.scheduledDate,dateBasis:arrival?'ARRIVAL_LOCAL_DATE':'DEPARTURE_LOCAL_DATE',origin:row.origin,destination:row.destination,departureTime:arrival?(existing.departureTime||''):row.scheduledLocalTime,arrivalTime:arrival?row.estimatedLocalTime:(existing.arrivalTime||''),terminal:row.terminalDisplayName,providerId:row.id,direction:row.direction,sourceState:'OFFICIAL_LINKED'}}
function draftFromFlight(row){return {id:null,revision:null,type:'ONE_WAY',name:`${row.originName||row.origin} 여행`,segments:[flightSegment(row,blankSegment())]}}
async function tripFormView(id,token){
  if(id){if(!(state.resumeDraft&&state.tripDraft?.id===id)){const trip=await api('/trips/'+encodeURIComponent(id));if(token!==state.routeToken)return;state.tripDraft={id:trip.id,revision:trip.revision,type:trip.type,name:trip.name,segments:trip.segments.map(item=>({...blankSegment(),...item,segmentId:item.segmentId||crypto.randomUUID()}))}}state.resumeDraft=false}
  else if(!state.tripDraft)state.tripDraft={id:null,revision:null,type:'ONE_WAY',name:'나의 여행',segments:[blankSegment()]};
  renderTripForm();
}
function renderTripForm(){const d=state.tripDraft;app.innerHTML=hero('TRAVEL WALLET',d.id?'여행 지갑 수정':'새 여행 지갑','날짜와 노선을 먼저 적고 필요한 정보만 더해보세요.')+`<section class="card form-card"><div class="form-head"><div><h2>${d.id?'여정 수정':'여정 기본 정보'}</h2><p class="muted">이 브라우저에서 만든 여행만 볼 수 있어요. 여권번호는 저장하지 마세요.</p></div><button class="secondary" data-route="/majoong/trips">저장한 여행 보기</button></div><div class="form-grid"><label class="field">여행 이름<input class="input" data-draft="name" value="${e(d.name)}" maxlength="120"></label><label class="field">여정 유형<select data-draft="type"><option value="ONE_WAY" ${d.type==='ONE_WAY'?'selected':''}>편도</option><option value="ROUND_TRIP" ${d.type==='ROUND_TRIP'?'selected':''}>왕복</option><option value="MULTI_CITY" ${d.type==='MULTI_CITY'?'selected':''}>다구간</option></select></label></div><div id="segmentList">${d.segments.map(segmentHtml).join('')}</div>${d.type==='MULTI_CITY'?'<button class="secondary wide" data-action="add-segment">＋ 구간 추가</button>':''}<div class="form-actions"><button class="secondary" data-route="/majoong/trips">취소</button><button class="primary" data-action="save-trip">여행 지갑에 저장</button></div><div id="tripMessage" aria-live="polite"></div></section>`;
  app.querySelectorAll('[data-draft],[data-segment]').forEach(el=>el.addEventListener('input',captureDraftInput));app.querySelector('[data-draft="type"]').addEventListener('change',changeTripType);
}
function segmentHtml(segment,index){const dateLabel=segment.dateBasis==='ARRIVAL_LOCAL_DATE'?'인천 도착일':'출발일';return `<fieldset class="segment-card"><div class="segment-head"><h3>${index+1}번째 구간</h3><div>${segment.providerId?'<span class="source-badge">공식 운항 연결됨</span>':'<span class="source-badge manual-badge">직접 입력</span>'}${state.tripDraft.type==='MULTI_CITY'&&state.tripDraft.segments.length>2?` <button class="text-button" type="button" data-action="remove-segment" data-index="${index}">삭제</button>`:''}</div></div><div class="segment-basic"><label class="field">${dateLabel}<input class="input" type="date" data-segment="date" data-index="${index}" value="${e(segment.date)}" required></label><label class="field">편명 <span class="muted">모르면 비워도 돼요</span><input class="input" data-segment="flightNumber" data-index="${index}" value="${e(segment.flightNumber)}" maxlength="20" placeholder="예: KE703"></label><label class="field">출발 공항<input class="input" data-segment="origin" data-index="${index}" value="${e(segment.origin)}" maxlength="3" placeholder="ICN" required></label><label class="field">도착 공항<input class="input" data-segment="destination" data-index="${index}" value="${e(segment.destination)}" maxlength="3" placeholder="NRT" required></label></div><details class="segment-details"><summary>예약·좌석·수하물 등 상세 정보</summary><div class="form-grid"><label class="field">항공사<input class="input" data-segment="airline" data-index="${index}" value="${e(segment.airline)}"></label><label class="field">예약번호<input class="input" data-segment="bookingReference" data-index="${index}" value="${e(segment.bookingReference)}" maxlength="40"></label><label class="field">출발 시각<input class="input" type="time" data-segment="departureTime" data-index="${index}" value="${e(segment.departureTime)}"></label><label class="field">도착 시각<input class="input" type="time" data-segment="arrivalTime" data-index="${index}" value="${e(segment.arrivalTime)}"></label><label class="field">터미널<input class="input" data-segment="terminal" data-index="${index}" value="${e(segment.terminal)}"></label><label class="field">게이트<input class="input" data-segment="gate" data-index="${index}" value="${e(segment.gate)}"></label><label class="field">좌석<input class="input" data-segment="seat" data-index="${index}" value="${e(segment.seat)}"></label><label class="field">수하물<input class="input" data-segment="baggage" data-index="${index}" value="${e(segment.baggage)}"></label></div><label class="field">메모<textarea class="input" data-segment="memo" data-index="${index}" maxlength="300">${e(segment.memo)}</textarea></label></details>${segment.origin==='ICN'||segment.destination==='ICN'?`<button class="text-button" type="button" data-action="lookup-segment" data-index="${index}">${e(segment.date)} 실제 운항편에서 찾기</button>`:'<p class="muted small">현재 공식 조회는 인천공항 구간만 지원합니다.</p>'}</fieldset>`}
function captureDraftInput(event){const el=event.target;if(el.dataset.draft)state.tripDraft[el.dataset.draft]=el.value;if(el.dataset.segment){const segment=state.tripDraft.segments[Number(el.dataset.index)];segment[el.dataset.segment]=['origin','destination','flightNumber','seat'].includes(el.dataset.segment)?el.value.toUpperCase():el.value}}
function changeTripType(event){const type=event.target.value,d=state.tripDraft;d.type=type;if(type==='ONE_WAY')d.segments=d.segments.slice(0,1);else if(type==='ROUND_TRIP'){if(d.segments.length<2){const first=d.segments[0];d.segments.push(blankSegment({date:first.date,origin:first.destination,destination:first.origin}))}d.segments=d.segments.slice(0,2)}else if(d.segments.length<2)d.segments.push(blankSegment({origin:d.segments[0].destination,destination:''}));renderTripForm()}
async function saveTrip(){const d=state.tripDraft,button=document.querySelector('[data-action="save-trip"]'),message=document.querySelector('#tripMessage');button.disabled=true;message.innerHTML='';try{const body={type:d.type,name:d.name.trim(),segments:d.segments,expectedRevision:d.revision};const trip=await api(d.id?'/trips/'+d.id:'/trips',{method:d.id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});state.tripDraft=null;toast('여행 지갑에 저장했어요.');navigate('/majoong/trips/'+trip.id)}catch(error){message.innerHTML=`<div class="notice error">${e(error.message)}</div>`;button.disabled=false}}

async function tripsView(token){app.innerHTML=hero('TRAVEL WALLET','내 여행 지갑','예정된 여행과 탑승 준비 정보를 한곳에서 확인하세요.')+`<div class="toolbar"><div><h2 class="section-title">저장한 여행</h2><p class="muted">이 브라우저에서 만든 여행입니다.</p></div><button class="primary" data-action="new-trip">＋ 새 여행</button></div><div class="tabs"><button data-action="trip-tab" data-value="upcoming" class="active">예정</button><button data-action="trip-tab" data-value="past">지난 여행</button><button data-action="trip-tab" data-value="all">전체</button><button data-action="trip-tab" data-value="trash">휴지통</button></div><label class="sr" for="tripFilter">여행 검색</label><input class="input search-mini" id="tripFilter" placeholder="여행명·공항 검색"><div id="tripList" class="wallet-list section"><div class="loading">여행 지갑을 불러오는 중이에요.</div></div>`;const trips=await api('/trips');if(token!==state.routeToken)return;state.trips=trips;state.tripTab='upcoming';state.tripFilter='';document.querySelector('#tripFilter').addEventListener('input',event=>{state.tripFilter=event.target.value;renderTrips()});renderTrips()}
function renderTrips(){const box=document.querySelector('#tripList');if(!box)return;const now=today(),term=(state.tripFilter||'').toUpperCase(),trash=state.tripTab==='trash';let items=state.trips.filter(trip=>{const dates=trip.segments.map(s=>s.date).filter(Boolean),last=dates.sort().at(-1)||'';const tab=state.tripTab||'upcoming';return (trash||tab==='all'||(tab==='upcoming'?last>=now:last<now))&&(!term||(trip.name+' '+trip.segments.map(s=>s.origin+' '+s.destination).join(' ')).toUpperCase().includes(term))}).sort((a,b)=>(a.segments[0]?.date||'').localeCompare(b.segments[0]?.date||''));box.innerHTML=items.length?items.map(trash?trashCard:walletCard).join(''):empty(trash?'🗑️':'🧳',trash?'휴지통이 비어 있어요':'표시할 여행이 없어요',trash?'삭제한 여행은 7일 동안 복원할 수 있어요.':'새 여행을 등록하거나 탭을 바꿔보세요.',trash?'':'<button class="primary" data-action="new-trip">첫 여행 등록하기</button>')}
function tripLabel(type){return {ONE_WAY:'편도',ROUND_TRIP:'왕복',MULTI_CITY:'다구간'}[type]||type}function dday(date){if(!date)return'날짜 미정';const diff=Math.round((new Date(date+'T12:00:00+09:00')-new Date(today()+'T12:00:00+09:00'))/86400000);return diff===0?'오늘 일정':diff>0?'D-'+diff:'일정 날짜 지남'}
function trashCard(trip){return `<article class="card meetup-card"><div><span class="manual-badge source-badge">휴지통</span><h2>${e(trip.name)}</h2><p class="muted">${e(trip.deletedAt?fmtTime(trip.deletedAt):'삭제 시각 확인 중')} · ${e(trip.purgeAt?fmtTime(trip.purgeAt):'7일 내')}까지 복원 가능</p></div><button class="primary" data-action="restore-trip" data-id="${e(trip.id)}">복원</button></article>`}
function walletCard(trip){const first=trip.segments[0]||{},last=trip.segments.at(-1)||{},routeLabel=trip.type==='ROUND_TRIP'?`${first.origin} ↔ ${first.destination}`:`${first.origin||'—'} → ${last.destination||'—'}`;return `<article class="wallet-card"><header><div><span class="wallet-chip">${tripLabel(trip.type)} · ${trip.state==='OFFICIAL_LINKED'?'공식 운항 연결':'확인 필요'}</span><h2>${e(trip.name)}</h2><p>${e(routeLabel)} · ${e(first.date)}${last.date&&last.date!==first.date?'–'+e(last.date):''}</p></div><strong class="dday">${e(dday(first.date))}</strong></header>${trip.segments.map((segment,index)=>walletSegment(trip,segment,index)).join('')}<div class="checklist">${[['identity','여권·신분증'],['ticket','항공권·예약번호'],['baggage','수하물 규정'],['transport','공항 이동수단']].map(([key,label])=>`<label><input type="checkbox" data-action="check-item" data-trip="${e(trip.id)}" data-key="${key}" ${checkState(trip.id)[key]?'checked':''}> ${label}</label>`).join('')}</div><div class="wallet-actions"><button class="secondary" data-action="edit-trip" data-id="${e(trip.id)}">수정</button><button class="secondary" data-action="export-ics" data-id="${e(trip.id)}">달력 파일</button><button class="danger" data-action="delete-trip" data-id="${e(trip.id)}">삭제</button></div></article>`}
function walletSegment(trip,segment,index){const booking=segment.bookingReference?(state.revealed.has(trip.id+'-'+index)?segment.bookingReference:'••••••'):'미입력';return `<section class="wallet-segment"><div class="route-line"><div><small>출발</small><div class="airport-code">${e(segment.origin)}</div><span>${e(segment.departureTime||'시간 미입력')}</span></div><div class="route-flight">✈<br>${e(segment.airline||'항공사 미입력')} · ${e(segment.flightNumber||'편명 미정')}</div><div><small>도착</small><div class="airport-code">${e(segment.destination)}</div><span>${e(segment.arrivalTime||'시간 미입력')}</span></div></div><div class="wallet-details"><div><small>날짜</small><b>${e(segment.date)}</b></div><div><small>예약번호</small><b class="masked">${e(booking)}</b>${segment.bookingReference?`<button class="text-button" data-action="reveal-booking" data-id="${e(trip.id)}" data-index="${index}">${state.revealed.has(trip.id+'-'+index)?'숨기기':'보기'}</button>`:''}</div><div><small>터미널·게이트</small><b>${e(segment.terminal||'미입력')} · ${e(segment.gate||'—')}</b></div><div><small>좌석</small><b>${e(segment.seat||'미입력')}</b></div><div><small>수하물</small><b>${e(segment.baggage||'미입력')}</b></div><div><small>자료</small><b>${segment.providerId?'공식 연결':'직접 입력'}</b></div></div>${segment.memo?`<p class="notice info">${e(segment.memo)}</p>`:''}<button class="secondary wide" data-action="lookup-trip-flight" data-id="${e(trip.id)}" data-index="${index}">${e(segment.date)} 운항 확인</button>${segment.destination==='ICN'&&segment.providerId?`<button class="secondary wide" data-action="trip-meetup" data-id="${e(trip.id)}" data-index="${index}">이 구간 마중방 만들기</button>`:''}</section>`}
function checkState(id){try{return JSON.parse(localStorage.getItem('majoong-check-'+id)||'{}')}catch{return{}}}

async function meetupsView(token){app.innerHTML=hero('MY MEETUPS','내 마중','진행 중인 마중방을 다시 열고 가족과 공유하세요.')+`<div class="toolbar"><div><h2 class="section-title">진행 중인 마중</h2><p class="muted">완료하면 공유 링크도 함께 종료됩니다.</p></div><button class="secondary" data-route="/majoong/">도착편 찾기</button></div><div class="tabs"><button class="active" data-action="meetup-tab" data-value="active">진행 중</button><button data-action="meetup-tab" data-value="completed">완료</button></div><div id="meetupList" class="meetup-list"><div class="loading">마중방을 불러오는 중이에요.</div></div>`;state.meetupState='active';state.meetups=await api('/meetups?state=active');if(token!==state.routeToken)return;renderMeetups()}
function renderMeetups(){const box=document.querySelector('#meetupList');box.innerHTML=state.meetups.length?state.meetups.map(item=>`<article class="card meetup-card"><div><span class="source-badge">${item.completed?'완료':'진행 중'}</span><h2>${e(item.flight)} · ${e(item.origin)} → ${e(item.destination)}</h2><p class="muted">${e(item.scheduledDate)} · 예상 ${e(item.estimated)} · ${e(item.terminal)} · 출구 ${e(item.exit)}</p><p>${e(statusLabel(item.status))}</p></div><button class="primary" data-action="open-meetup" data-id="${e(item.id)}">열기</button></article>`).join(''):empty('☁️',state.meetupState==='active'?'진행 중인 마중이 없어요':'완료한 마중이 없어요','도착 항공편을 선택해 마중방을 만들 수 있어요.','<button class="primary" data-route="/majoong/">도착편 찾기</button>')}
async function meetupDetailView(id,token){app.innerHTML='<div class="loading">마중방을 불러오는 중이에요.</div>';const m=await api('/meetups/'+encodeURIComponent(id));if(token!==state.routeToken)return;renderMeetupDetail(m)}
function renderMeetupDetail(m){app.innerHTML=hero('MY MEETUP',`${e(m.flight)} 마중방`,`${e(m.origin)} → ${e(m.destination)} · ${e(m.scheduledDate)}`)+`<section class="section content-grid"><div class="card"><span class="source-badge">공식 운항 최근 확인 ${e(fmtTime(m.sourceObservedAt))}</span><div class="big-time">${e(m.estimated)}</div><p class="muted">예정 ${e(m.scheduled)} · ${e(m.terminal)} · 입국 출구 ${e(m.exit)} · 수취대 ${e(m.baggage)}</p><h2>여행자가 알려주는 상태</h2><div class="status-grid">${[['IMMIGRATION','입국심사 중'],['WAITING_BAGGAGE','짐 기다리는 중'],['OUTSIDE','밖으로 나왔어요'],['MET','만났어요']].map(([value,label])=>`<button class="secondary ${m.status===value?'active':''}" data-action="meetup-status" data-id="${e(m.id)}" data-value="${value}" data-revision="${m.revision}">${label}</button>`).join('')}</div><p class="muted small">여행자 상태 갱신 ${e(fmtTime(m.travelerUpdatedAt))}</p><h2>함께 정한 만남 장소</h2><div class="form-grid"><label class="field">터미널<input class="input" id="pointTerminal" value="${e(m.pointTerminal||m.terminal)}"></label><label class="field">공개구역·층<input class="input" id="pointArea" value="${e(m.pointArea)}" placeholder="예: 1층 공개구역"></label><label class="field">출구<input class="input" id="pointExit" value="${e(m.pointExit||m.exit)}"></label><label class="field">랜드마크<input class="input" id="pointLandmark" value="${e(m.pointLandmark)}" placeholder="예: 안내데스크 옆"></label></div><label class="field">메모<textarea class="input" id="pointNote" maxlength="300">${e(m.note)}</textarea></label><button class="primary" data-action="save-point" data-id="${e(m.id)}" data-revision="${m.revision}">만남 장소 저장</button></div><aside class="card sticky"><h2>가족에게 공유</h2><p class="muted">항공편·여행자 상태·공개한 장소만 보이며 24시간 후 종료됩니다.</p><button class="primary wide" data-action="share-meetup" data-id="${e(m.id)}">읽기 전용 링크 만들기</button><div id="shareResult"></div><button class="secondary wide" data-route="/majoong/meetups">내 마중 목록</button></aside></section>`}

async function sharedView(token){const shareToken=location.hash.replace('#token=','');if(!shareToken)return navigate('/majoong/',{replace:true});let stopped=false;const stop=()=>{stopped=true;clearTimeout(state.shareTimer)};async function load(){try{const data=await api('/shares/exchange',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:shareToken})});if(token!==state.routeToken||stopped)return;app.innerHTML=`<section class="shared-summary"><div class="shared-hero"><span class="eyebrow">읽기 전용 마중 현황</span><h1>${e(data.flight.displayNumber)} · ${e(data.flight.origin)} → ${e(data.flight.destination)}</h1><div class="big-time">${e(data.arrival.estimatedLocalTime)}</div><p>${e(data.arrival.date)} · 예정 ${e(data.arrival.scheduledLocalTime)}</p></div><div class="card section shared-place"><h2>${e(data.airportInfo.terminal)} · 입국 출구 ${e(data.airportInfo.arrivalExit)}</h2><p>수하물 수취대 ${e(data.airportInfo.baggageCarousel)}</p><p class="muted">공식 운항 확인 ${e(fmtTime(data.sourceObservedAt))}</p></div><div class="card section"><h2>여행자가 알려준 상태</h2><p class="big-time">${e(statusLabel(data.traveler.status))}</p><p class="muted">갱신 ${e(fmtTime(data.traveler.updatedAt))}</p><h2>만남 장소</h2><p>${e([data.meetingPoint.terminal,data.meetingPoint.publicArea,data.meetingPoint.exitLabel,data.meetingPoint.landmark].filter(Boolean).join(' · ')||'아직 정하지 않았어요.')}</p><p>${e(data.meetingNote)}</p><a class="secondary wide" href="https://www.airport.kr/geomap/ap_ko/view.do?type=2&alertType=0&tmnlId=P01" target="_blank" rel="noopener noreferrer" style="display:block;text-align:center;text-decoration:none">공식 공항지도</a><p class="muted small">이 화면은 읽기 전용이며 15초마다 상태를 다시 확인합니다.</p></div></section>`;state.shareTimer=setTimeout(load,15000)}catch(error){stop();if(token!==state.routeToken)return;if(error.status===410)app.innerHTML=empty('☁️','공유가 종료됐어요','새 링크가 필요하면 여행자에게 요청해 주세요.','<button class="primary" data-route="/majoong/">서비스 홈</button>');else app.innerHTML=`${empty('↻','잠시 연결이 불안정해요',error.message,'<button class="primary" data-action="retry-shared">다시 시도</button>')}`}}await load()}

async function showNotifications(){closeNotifications();const panel=document.createElement('section');panel.id='notificationPanel';panel.className='notification-panel';panel.innerHTML='<header><h2>운항 변경 알림</h2><button class="text-button" data-action="close-notifications">닫기</button></header><div class="loading">불러오는 중이에요.</div>';document.body.append(panel);try{const items=await api('/notifications'),watches=await api('/watches');panel.innerHTML=`<header><h2>운항 변경 알림</h2><button class="text-button" data-action="close-notifications">닫기</button></header>${items.length?items.map(item=>`<article class="notification-item ${item.read?'':'unread'}"><strong>${e(item.title)}</strong><p>${e(item.message)}</p><small class="muted">${e(fmtTime(item.createdAt))}</small>${item.read?'':`<button class="text-button" data-action="read-notification" data-id="${e(item.id)}">읽음</button>`}</article>`).join(''):'<p class="muted">새 변경 알림이 없어요.</p>'}<h3>관심 항공편 ${watches.length}개</h3>${watches.map(w=>`<p>${e(w.flight)} · ${e(w.scheduledDate)} <button class="text-button" data-action="delete-watch" data-id="${e(w.id)}">해제</button></p>`).join('')}`;updateNoticeCount(items)}catch(error){panel.innerHTML+=`<p class="notice error">${e(error.message)}</p>`}}
function closeNotifications(){document.querySelector('#notificationPanel')?.remove()}function updateNoticeCount(items){const count=items.filter(item=>!item.read).length,badge=document.querySelector('#noticeCount');badge.textContent=count;badge.hidden=!count}

document.addEventListener('click',async event=>{
  const routeButton=event.target.closest('[data-route]');if(routeButton){event.preventDefault();state.tripDraft=null;navigate(routeButton.dataset.route);return}
  const button=event.target.closest('[data-action]');if(!button)return;const action=button.dataset.action;
  try{
    if(action==='notifications')return showNotifications();if(action==='close-notifications')return closeNotifications();if(action==='retry-route')return route();if(action==='retry-shared')return sharedView(state.routeToken);
    if(action==='direction'){document.querySelectorAll('[data-action="direction"]').forEach(item=>item.setAttribute('aria-pressed',String(item===button)));document.querySelector('#dateLabel').textContent=button.dataset.value==='ARRIVAL'?'도착일':'출발일';return searchFlights()}
    if(action==='quick-date'){document.querySelector('#flightDate').value=offsetDate(Number(button.dataset.value));return searchFlights()}
    if(action==='search')return searchFlights();if(action==='clear-filter'){state.filter='';document.querySelector('#resultFilter').value='';state.displayLimit=50;return renderFlights()}
    if(action==='more-flights'){state.displayLimit+=50;return renderFlights()}if(action==='select-flight')return selectFlight(button.dataset.id);if(action==='close-detail'){document.querySelector('#detailColumn').classList.remove('open');const params=new URLSearchParams(location.search);params.delete('flight');history.replaceState({},'',location.pathname+(params.toString()?'?'+params:''));return}
    if(action==='cancel-linking'){state.linking=null;return navigate(state.tripDraft?.id?'/majoong/trips/'+state.tripDraft.id:'/majoong/trips/new')}
    if(action==='add-flight-trip'){state.linking=null;state.tripDraft=draftFromFlight(state.selected);return navigate('/majoong/trips/new')}
    if(action==='link-flight-trip'){const link=state.linking,row=state.selected;if(!link||!row)throw new Error('연결할 여행 구간을 다시 선택해 주세요.');const segment=state.tripDraft?.segments?.[link.index];if(!segment)throw new Error('여행 구간을 다시 열어 주세요.');const mismatch=segment.origin!==row.origin||segment.destination!==row.destination||segment.date!==row.scheduledDate;if(mismatch&&!confirm('기존 구간의 공항 또는 날짜가 선택한 항공편과 달라요. 공식 항공편 정보로 바꿀까요?'))return;state.tripDraft.segments[link.index]=flightSegment(row,segment);state.linking=null;state.resumeDraft=true;return navigate(link.returnPath)}
    if(action==='create-meetup'){button.disabled=true;const row=state.selected,m=await api('/meetups',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({providerId:row.id,scheduledDate:row.scheduledDate,direction:row.direction})});return navigate('/majoong/meetups/'+m.id)}
    if(action==='watch-flight'){button.disabled=true;const row=state.selected;await api('/watches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({providerId:row.id,scheduledDate:row.scheduledDate,direction:row.direction})});toast('변경 알림함에 추가했어요.');button.textContent='알림함에 추가됨';return}
    if(action==='new-trip'){state.tripDraft=null;return navigate('/majoong/trips/new')}if(action==='add-segment'){state.tripDraft.segments.push(blankSegment({origin:state.tripDraft.segments.at(-1).destination}));return renderTripForm()}if(action==='remove-segment'){state.tripDraft.segments.splice(Number(button.dataset.index),1);return renderTripForm()}if(action==='save-trip')return saveTrip();if(action==='edit-trip'){state.tripDraft=null;return navigate('/majoong/trips/'+button.dataset.id)}
    if(action==='trip-tab'){const next=button.dataset.value;state.tripTab=next;document.querySelectorAll('[data-action="trip-tab"]').forEach(item=>item.classList.toggle('active',item===button));state.trips=await api(next==='trash'?'/trips?state=trash':'/trips?state=active');return renderTrips()}
    if(action==='reveal-booking'){const key=button.dataset.id+'-'+button.dataset.index;state.revealed.has(key)?state.revealed.delete(key):state.revealed.add(key);return renderTrips()}
    if(action==='check-item'){const current=checkState(button.dataset.trip);current[button.dataset.key]=button.checked;localStorage.setItem('majoong-check-'+button.dataset.trip,JSON.stringify(current));return}
    if(action==='delete-trip'){if(!confirm('이 여행을 휴지통으로 옮길까요? 7일 안에는 복원할 수 있어요.'))return;await api('/trips/'+button.dataset.id,{method:'DELETE'});state.trips=state.trips.filter(item=>item.id!==button.dataset.id);toast('여행을 휴지통으로 옮겼어요.');return renderTrips()}
    if(action==='restore-trip'){await api('/trips/'+button.dataset.id+'/restore',{method:'POST'});state.trips=state.trips.filter(item=>item.id!==button.dataset.id);toast('여행을 복원했어요.');return renderTrips()}
    if(action==='lookup-trip-flight'){const trip=state.trips.find(item=>item.id===button.dataset.id),segment=trip.segments[Number(button.dataset.index)],direction=segment.origin==='ICN'?'DEPARTURE':segment.destination==='ICN'?'ARRIVAL':'';if(!direction)return toast('현재는 인천공항 구간만 조회할 수 있어요.');return navigate('/majoong/?'+new URLSearchParams({date:segment.date,direction,q:segment.flightNumber||(segment.destination==='ICN'?segment.origin:segment.destination)}))}
    if(action==='lookup-segment'){const index=Number(button.dataset.index),segment=state.tripDraft.segments[index],direction=segment.origin==='ICN'?'DEPARTURE':segment.destination==='ICN'?'ARRIVAL':'';if(!direction)return toast('현재는 인천공항 구간만 조회할 수 있어요.');state.linking={index,returnPath:state.tripDraft.id?'/majoong/trips/'+state.tripDraft.id:'/majoong/trips/new',label:`${index+1}번째`};return navigate('/majoong/?'+new URLSearchParams({date:segment.date,direction,q:segment.flightNumber||''}))}
    if(action==='export-ics'){const trip=state.trips.find(item=>item.id===button.dataset.id);return exportIcs(trip)}
    if(action==='trip-meetup'){const trip=state.trips.find(item=>item.id===button.dataset.id),segment=trip.segments[Number(button.dataset.index)];if(segment.direction!=='ARRIVAL')return toast('마중방은 인천 도착편에서만 만들 수 있어요.');const m=await api('/meetups',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({providerId:segment.providerId,scheduledDate:segment.date,direction:'ARRIVAL'})});return navigate('/majoong/meetups/'+m.id)}
    if(action==='open-meetup')return navigate('/majoong/meetups/'+button.dataset.id);if(action==='meetup-tab'){state.meetupState=button.dataset.value;document.querySelectorAll('[data-action="meetup-tab"]').forEach(item=>item.classList.toggle('active',item===button));state.meetups=await api('/meetups?state='+state.meetupState);return renderMeetups()}
    if(action==='meetup-status'){if(button.dataset.value==='MET'&&!confirm('만남을 완료하면 공유 링크도 종료됩니다. 완료할까요?'))return;const path=button.dataset.value==='MET'?`/meetups/${button.dataset.id}/complete`:`/meetups/${button.dataset.id}/traveler-status`,body=button.dataset.value==='MET'?{expectedVersion:Number(button.dataset.revision)}:{status:button.dataset.value,expectedVersion:Number(button.dataset.revision)};const m=await api(path,{method:button.dataset.value==='MET'?'POST':'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});toast('상태를 저장했어요.');return renderMeetupDetail(m)}
    if(action==='save-point'){const body={terminal:document.querySelector('#pointTerminal').value,publicArea:document.querySelector('#pointArea').value,exitLabel:document.querySelector('#pointExit').value,landmark:document.querySelector('#pointLandmark').value,note:document.querySelector('#pointNote').value,expectedVersion:Number(button.dataset.revision)};const m=await api('/meetups/'+button.dataset.id+'/meeting-point',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});toast('만남 장소를 저장했어요.');return renderMeetupDetail(m)}
    if(action==='share-meetup'){const result=await api('/meetups/'+button.dataset.id+'/shares',{method:'POST'}),url=location.origin+result.url;document.querySelector('#shareResult').innerHTML=`<div class="share-box"><input class="input" value="${e(url)}" readonly aria-label="읽기 전용 공유 링크"><button class="secondary" data-action="copy-share">복사</button></div><p class="muted small">만료 ${e(fmtTime(result.expiresAt))}</p>`;return}
    if(action==='copy-share'){const input=button.previousElementSibling;try{await navigator.clipboard.writeText(input.value);toast('공유 링크를 복사했어요.')}catch{input.select();toast('링크를 선택했어요. 직접 복사해 주세요.')}return}
    if(action==='read-notification'){await api('/notifications/'+button.dataset.id+'/read',{method:'POST'});return showNotifications()}if(action==='delete-watch'){await api('/watches/'+button.dataset.id,{method:'DELETE'});toast('관심 항공편에서 해제했어요.');return showNotifications()}
  }catch(error){toast(error.message)}
});

function exportIcs(trip){const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Majoong Cloud//KO'];for(const segment of trip.segments){const date=segment.date.replaceAll('-',''),start=segment.departureTime?date+'T'+segment.departureTime.replace(':','')+'00':date;lines.push('BEGIN:VEVENT','UID:'+segment.segmentId+'@majoong-cloud','DTSTART'+(segment.departureTime?';TZID=Asia/Seoul:':';VALUE=DATE:')+start,'SUMMARY:'+escapeIcs((segment.flightNumber||'항공편')+' '+segment.origin+' → '+segment.destination),'DESCRIPTION:'+escapeIcs('마중구름에서 내보낸 일정입니다. 자동 동기화되지 않습니다.'),'END:VEVENT')}lines.push('END:VCALENDAR');const blob=new Blob([lines.join('\r\n')],{type:'text/calendar;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(trip.name||'여행')+'.ics';a.click();URL.revokeObjectURL(url)}function escapeIcs(value){return String(value).replaceAll('\\','\\\\').replaceAll(',','\\,').replaceAll(';','\\;').replaceAll('\n','\\n')}

window.addEventListener('popstate',route);document.addEventListener('keydown',event=>{if(event.key==='Escape'){document.querySelector('#detailColumn')?.classList.remove('open');closeNotifications()}});route();showNotificationsCount();async function showNotificationsCount(){try{updateNoticeCount(await api('/notifications'))}catch{}}
